# -*- coding: utf-8 -*-
"""Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cnz7cUbUQL-Mk6ADglEcYLGQIs4lg8Uf
"""

def check_profanity(profane_words, data):

  """
  A function to calculates and returns the degree of profanity for each line a dataset.
  The degree of profanity is caluclated as the ratio of the number of profane words and the total number of words in a sentence. 

  Parameters
  ----------

  profane_words: list 
                List of profane words manually created.
  data: List
                List of sentences that needs to be chekced.

  Returns
  -------
  profane_degrees: dict
                List of degrees of profanities for each sentence

  """

  # List of degrees of profanity in each line
  profane_degrees = {}

  # For every line in the dataset
  for line in data:
    
    profane_count = 0

    # For every word in the line
    for word in line.split(" "):
      
      # Check if this word is a profane word
      if word in profane_words:
        profane_count += 1

    profane_degree = profane_count/len(line.split(" "))
    profane_degrees[line] = profane_degree


  return profane_degrees


def get_data_from_file(path):
  
  """
  A function to read and return data from text files.

  Parameters
  ----------

  path: string 
          path to text file.
  
  Returns
  -------
  data: list
          list of data read from read from text file.
  """

  # Open and read text file
  with open(path, "r") as f:

    lines = f.readlines()
    
    # Remove '\n' from lines
    data = [line[:-1] for line in lines]
    
    f.close()
  
  return data

def main():

  data_path = "text.txt"
  profane_word_path = "profane.txt"
  
  # Read data from text files
  data = get_data_from_file(data_path)
  profane_words = get_data_from_file(profane_word_path)

  # Get degrees of profanity
  profane_degrees = check_profanity(profane_words, data)
  
  print(profane_degrees)

main()

